import { HotelSettings, Room, MenuItem, BanquetHall, NearbyPlace, GalleryItem, SpecialOffer } from '../types';

export const initialHotelSettings: HotelSettings = {
  name: 'Hotel Udika Palace',
  tagline: 'Stay. Dine. Celebrate.',
  supportingText: 'A refined stay in the heart of Waidhan, designed for comfortable stays, memorable dining and meaningful celebrations.',
  address: 'Thana Road, Waidhan',
  city: 'Waidhan, Singrauli',
  state: 'Madhya Pradesh',
  pincode: '486886',
  country: 'India',
  phone: '+919522001777',
  phoneDisplay: '+91 95220 01777',
  whatsappNumber: '919522001777',
  whatsappDisplay: '+91 95220 01777',
  email: 'info@hoteludikapalace.com',
  bookingEmail: 'reservations@hoteludikapalace.com',
  coordinates: {
    lat: 24.0628,
    lng: 82.6322,
  },
  checkInTime: '12:00 PM',
  checkOutTime: '11:00 AM',
  restaurantName: 'Zayka Restaurant',
  heroImageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=2000&q=85',
  whatsappMessageTemplate: 'Hello Hotel Udika Palace, I would like to make an enquiry regarding a stay. Check-in: {checkIn}, Check-out: {checkOut}, Guests: {guests}, Room: {room}.',
  socialLinks: {
    instagram: 'https://instagram.com/hoteludikapalace',
    facebook: 'https://facebook.com/hoteludikapalace',
    googleBusiness: 'https://maps.google.com/?cid=udikapalace',
  },
};

export const initialRooms: Room[] = [
  {
    id: 'room-std-nonac',
    name: 'Standard Room',
    category: 'Standard',
    ac: false,
    shortDescription: 'Subtle and functional room designed for budget-conscious business and solo visitors.',
    detailedDescription: 'Our Standard Room offers peaceful simplicity and dependable comfort in the core of Waidhan. Equipped with twin or queen bedding, sanitized en-suite bathroom, high-speed Wi-Fi, and 24-hour room dining availability.',
    bedType: 'Queen Bed or Twin Beds',
    maxAdults: 2,
    maxChildren: 1,
    roomSizeSqFt: 220,
    baseRatePerNight: 1650,
    showPrice: true,
    featuredImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'High-Speed Wi-Fi',
      'En-suite Bathroom & Hot Water',
      'Flat Screen Television',
      'Complimentary Mineral Water',
      'Daily Housekeeping',
      '24/7 Room Service Access',
    ],
    policies: [
      'Standard Check-in: 12:00 PM, Check-out: 11:00 AM',
      'Government ID proof required at check-in (Aadhaar / Voter ID / Passport)',
      'Couples & families welcomed with valid identification',
    ],
    totalInventory: 10,
    isActive: true,
    isFeatured: false,
    order: 1,
  },
  {
    id: 'room-deluxe-ac',
    name: 'Deluxe Room',
    category: 'Deluxe',
    ac: true,
    shortDescription: 'Air-conditioned comfort with refined contemporary furnishings and warm lighting.',
    detailedDescription: 'Thoughtfully designed with climate-controlled air-conditioning, upholstered seating, and modern wooden accents. Ideal for industrial delegates and leisure guests visiting the Singrauli energy corridor.',
    bedType: 'King Size Bed',
    maxAdults: 2,
    maxChildren: 1,
    roomSizeSqFt: 280,
    baseRatePerNight: 2350,
    showPrice: true,
    featuredImage: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Individual Climate Control (AC)',
      'High-Speed Wi-Fi',
      '32-inch LED HD TV with Satellite Channels',
      'Work Desk & Ergonomic Seating',
      'Tea & Coffee Maker',
      'Modern Shower with Premium Toiletries',
      '24/7 In-room Dining',
    ],
    policies: [
      'Standard Check-in: 12:00 PM, Check-out: 11:00 AM',
      'Government ID required for all adult guests',
      'Late check-out subject to availability',
    ],
    totalInventory: 14,
    isActive: true,
    isFeatured: true,
    order: 2,
  },
  {
    id: 'room-super-deluxe-ac',
    name: 'Super Deluxe Room',
    category: 'Super Deluxe',
    ac: true,
    shortDescription: 'Generous layout featuring cozy lounge seating and serene garden/city sightlines.',
    detailedDescription: 'Offers elevated space and plush bedding with superior acoustic insulation, dedicated lounging corner, and warm hospitality appointments for an indulgent stay in Waidhan.',
    bedType: 'Custom King Bed',
    maxAdults: 3,
    maxChildren: 2,
    roomSizeSqFt: 360,
    baseRatePerNight: 3100,
    showPrice: true,
    featuredImage: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Silent Inverter Air-Conditioning',
      'High-Speed Dedicated Wi-Fi',
      '43-inch Smart LED TV',
      'Lounge Sofa & Coffee Table',
      'Tea/Coffee Amenity Station',
      'Mini Refrigerator',
      'Executive Vanity Kit & Bathrobe',
      'Priority Room Service',
    ],
    policies: [
      'Standard Check-in: 12:00 PM, Check-out: 11:00 AM',
      'Complimentary early check-in by 1 hour (subject to availability)',
      'Valid Government Photo Identification is mandatory',
    ],
    totalInventory: 8,
    isActive: true,
    isFeatured: true,
    order: 3,
  },
  {
    id: 'room-executive-suite',
    name: 'Executive Room',
    category: 'Executive',
    ac: true,
    shortDescription: 'Our hallmark accommodation for senior business leaders, dignitaries and families.',
    detailedDescription: 'The pinnacle of Udika hospitality. Expansive architectural footprint featuring hand-picked Indian textile touches, distinct meeting & dining corner, luxury master bath, and dedicated concierge care.',
    bedType: 'Grand Royal King Bed',
    maxAdults: 3,
    maxChildren: 2,
    roomSizeSqFt: 460,
    baseRatePerNight: 4200,
    showPrice: true,
    featuredImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80',
    ],
    amenities: [
      'Central Climate Control',
      'Premium High-Speed Wi-Fi',
      '50-inch 4K Smart Television',
      'Separate Seating & Living Lounge',
      'In-Room Safe & Refrigerator',
      'Gourmet Tea & Roasted Coffee Station',
      'Luxury Rain Shower & Plush Towels',
      'Daily Turn-Down Service',
      'VIP In-Room Dining Menu',
    ],
    policies: [
      'Standard Check-in: 12:00 PM, Check-out: 11:00 AM',
      'Valid Photo Identification required',
      'Customized catering requests entertained upon notice',
    ],
    totalInventory: 4,
    isActive: true,
    isFeatured: true,
    order: 4,
  },
];

export const initialMenuItems: MenuItem[] = [
  {
    id: 'menu-1',
    name: 'Paneer Tikka Angara',
    description: 'Fresh cottage cheese cubes marinated in smoked hung curd, Kashmiri deggi mirch, and roasted spices cooked in clay tandoor.',
    category: 'Soups & Starters',
    cuisine: 'Indian',
    price: 280,
    isVeg: true,
    isChefSpecial: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Medium',
  },
  {
    id: 'menu-2',
    name: 'Murgh Malai Tikka',
    description: 'Tender chicken morsels soaked in clotted cream, cardamom, cashew paste, and light green chilies char-grilled to perfection.',
    category: 'Soups & Starters',
    cuisine: 'Indian',
    price: 360,
    isVeg: false,
    isChefSpecial: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Mild',
  },
  {
    id: 'menu-3',
    name: 'Crispy Chilli Baby Corn & Mushroom',
    description: 'Wok-tossed fresh golden baby corn and mushrooms tossed in garlic, scallions, and tangy oriental soy glaze.',
    category: 'Chinese & Tandoor',
    cuisine: 'Chinese',
    price: 240,
    isVeg: true,
    isChefSpecial: false,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Medium',
  },
  {
    id: 'menu-4',
    name: 'Udika Special Dal Makhani',
    description: 'Whole black urad lentils slow-simmered overnight over charcoal embers with fresh churned butter and hand-crushed tomatoes.',
    category: 'Main Course',
    cuisine: 'Indian',
    price: 260,
    isVeg: true,
    isChefSpecial: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Mild',
  },
  {
    id: 'menu-5',
    name: 'Kadhai Paneer Nizami',
    description: 'Cottage cheese batons tossed with bell peppers, crushed coriander seeds, and whole dried red chillies in thick masala.',
    category: 'Main Course',
    cuisine: 'Indian',
    price: 290,
    isVeg: true,
    isChefSpecial: false,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Medium',
  },
  {
    id: 'menu-6',
    name: 'Butter Chicken Aslam Style',
    description: 'Smoked bone-in chicken braised in silky velvety makhani gravy infused with fenugreek leaves and mountain honey.',
    category: 'Main Course',
    cuisine: 'Indian',
    price: 390,
    isVeg: false,
    isChefSpecial: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Mild',
  },
  {
    id: 'menu-7',
    name: 'Dum Handi Gosht Biryani',
    description: 'Fragrant long-grain aged basmati rice cooked on slow dum with aromatic spices, brown onions, and tender lamb cuts.',
    category: 'Biryani & Rice',
    cuisine: 'Indian',
    price: 430,
    isVeg: false,
    isChefSpecial: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Medium',
  },
  {
    id: 'menu-8',
    name: 'Subz Awadhi Dum Biryani',
    description: 'Seasonal crisp vegetables and paneer layered with saffron basmati rice, mint leaves, and kewra essence. Served with burani raita.',
    category: 'Biryani & Rice',
    cuisine: 'Indian',
    price: 270,
    isVeg: true,
    isChefSpecial: false,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Mild',
  },
  {
    id: 'menu-9',
    name: 'Chilli Chicken Gravy with Hakka Noodles',
    description: 'Classic wok-tossed spicy Indo-Chinese chicken paired with soft noodles, shredded cabbage, and scallions.',
    category: 'Chinese & Tandoor',
    cuisine: 'Chinese',
    price: 320,
    isVeg: false,
    isChefSpecial: false,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    spicyLevel: 'Spicy',
  },
  {
    id: 'menu-10',
    name: 'Garlic & Cheese Naan Basket',
    description: 'Assorted clay oven breads: Garlic Naan, Butter Roti, Laccha Paratha and Missi Roti.',
    category: 'Breads',
    cuisine: 'Indian',
    price: 180,
    isVeg: true,
    isChefSpecial: false,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'menu-11',
    name: 'Shahi Gulab Jamun with Rabdi',
    description: 'Warm melt-in-mouth milk dumplings soaked in saffron syrup, crowned with chilled thickened rabdi and toasted pistachios.',
    category: 'Desserts & Beverages',
    cuisine: 'Indian',
    price: 150,
    isVeg: true,
    isChefSpecial: true,
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80',
  },
];

export const initialBanquets: BanquetHall[] = [
  {
    id: 'hall-raj-darbar',
    name: 'The Grand Udika Ballroom',
    tagline: 'Singrauli’s premier destination for weddings, galas, and landmark celebrations',
    description: 'A pillar-free, high-ceiling banquet hall appointed with crystal chandeliers, acoustic wall paneling, and an expansive stage. Designed to host royal wedding receptions, sangeet evenings, and grand anniversary banquets.',
    seatingCapacity: '250 - 350 Guests',
    floatingCapacity: 'Up to 500 Guests',
    parkingCapacity: 'Dedicated on-site parking for 60+ vehicles',
    cateringInfo: 'Full in-house catering with customized multi-cuisine live counters, traditional vegetarian feasts, and royal Mughlai menus.',
    features: [
      'Pillarless Grand Layout with High Ceilings',
      'Advanced Ambient & Stage Lighting Rig',
      'Acoustically Treated Audio & PA System',
      'Green Rooms for Bride & Groom',
      'High-Capacity Centralized Air Conditioning',
      'Dedicated Entrance & Valet Assistance',
    ],
    images: [
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80',
    ],
    suitableFor: ['Weddings & Receptions', 'Engagement & Sangeet', 'Grand Family Gatherings', 'Annual Corporate Galas'],
    isActive: true,
  },
  {
    id: 'hall-crystal-lounge',
    name: 'The Senate Conference & Boardroom',
    tagline: 'Sleek, productive meeting environments for corporate leaders and delegates',
    description: 'Equipped with HD projection systems, conference microphones, high-speed Wi-Fi, and personalized tea/coffee banquet service for NTPC, NCL, coal mining executives, and regional business summits.',
    seatingCapacity: '40 - 80 Delegates',
    floatingCapacity: 'Up to 100 Guests',
    parkingCapacity: 'Executive priority parking',
    cateringInfo: 'Executive lunch buffet, coffee break high-tea, and bespoke dining.',
    features: [
      'Smart AV Integration & Projector Screen',
      'High-Speed Enterprise Wi-Fi',
      'U-shape, Theater, or Classroom setups',
      'Stationery & Mineral Water Service',
      'Soundproof Executive Atmosphere',
    ],
    images: [
      'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80',
    ],
    suitableFor: ['Corporate Seminars', 'Mining & Energy Delegations', 'Board Meetings', 'Training Workshops'],
    isActive: true,
  },
];

export const initialNearbyPlaces: NearbyPlace[] = [
  {
    id: 'place-malhar-park',
    name: 'Malhar Park',
    category: 'Nature & Parks',
    shortDescription: 'Lush manicured public park with walking promenades, gentle fountains, and sunset leisure for families.',
    heroImage: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?auto=format&fit=crop&w=800&q=80',
    lat: 24.0841,
    lng: 82.6415,
    approxDistanceKm: 3.8,
    approxDriveMinutes: 10,
    address: 'Near Collectorate, Waidhan, MP',
    openingHours: '06:00 AM – 08:30 PM daily',
    travelTips: 'Pleasant during early morning walks and late afternoons.',
    googleMapsQuery: 'Malhar Park Waidhan Singrauli',
    isFeatured: true,
  },
  {
    id: 'place-ntpc-lake-park',
    name: 'Lake Park / NTPC Vindhyanagar',
    category: 'Nature & Parks',
    shortDescription: 'Sprawling scenic township lake with peaceful water vistas and manicured landscaped gardens.',
    heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    lat: 24.1162,
    lng: 82.6989,
    approxDistanceKm: 14.5,
    approxDriveMinutes: 25,
    address: 'NTPC Vindhyanagar Township, Singrauli',
    openingHours: '07:00 AM – 07:00 PM',
    travelTips: 'Great photography spot along the quiet embankment.',
    googleMapsQuery: 'Lake Park NTPC Vindhyanagar',
    isFeatured: true,
  },
  {
    id: 'place-mudwani-dam',
    name: 'Mudwani Dam Eco Park',
    category: 'Waterfalls & Lakes',
    shortDescription: 'Eco-tourism retreat surrounded by forested hills and scenic catchment reservoir waters.',
    heroImage: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
    lat: 24.1524,
    lng: 82.5982,
    approxDistanceKm: 18.2,
    approxDriveMinutes: 35,
    address: 'Mudwani Dam, Singrauli District, MP',
    openingHours: 'Open during daylight hours',
    travelTips: 'Best visited during monsoon and winter months for scenic water views.',
    googleMapsQuery: 'Mudwani Dam Eco Park Singrauli',
    isFeatured: true,
  },
  {
    id: 'place-central-park-rose',
    name: 'Central Park & Rose Garden',
    category: 'Nature & Parks',
    shortDescription: 'Vibrant municipal garden boasting seasonal rose cultivars, shaded pergolas, and children play zones.',
    heroImage: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    lat: 24.0722,
    lng: 82.6481,
    approxDistanceKm: 2.5,
    approxDriveMinutes: 7,
    address: 'Central Corridor, Waidhan, MP',
    openingHours: '06:30 AM – 08:00 PM',
    travelTips: 'Convenient 5 to 7 minute drive from Hotel Udika Palace.',
    googleMapsQuery: 'Rose Garden Waidhan',
    isFeatured: true,
  },
  {
    id: 'place-chandan-water-park',
    name: 'Chandan Global Water Park',
    category: 'Entertainment',
    shortDescription: 'Exciting regional amusement hub with water slides, wave pool, and weekend recreational entertainment.',
    heroImage: 'https://images.unsplash.com/photo-1582650625119-3a31f8418b7d?auto=format&fit=crop&w=800&q=80',
    lat: 24.0321,
    lng: 82.5843,
    approxDistanceKm: 9.2,
    approxDriveMinutes: 18,
    address: 'Main Highway, Singrauli Region, MP',
    openingHours: '10:30 AM – 06:00 PM (Seasonal)',
    travelTips: 'Great family outing destination on warm days.',
    googleMapsQuery: 'Chandan Global Water Park Waidhan',
    isFeatured: false,
  },
  {
    id: 'place-khadiya-waterfall',
    name: 'Khadiya Scenic Environs & Waterfalls',
    category: 'Waterfalls & Lakes',
    shortDescription: 'Rugged natural gorges and seasonal cascades nestled in the Vindhyachal hill folds.',
    heroImage: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
    lat: 24.1685,
    lng: 82.7245,
    approxDistanceKm: 22.0,
    approxDriveMinutes: 40,
    address: 'Northern Ridges, Singrauli District',
    openingHours: 'Daylight visit advised',
    travelTips: 'Wear sturdy footwear and travel by private car or cab.',
    googleMapsQuery: 'Khadiya Singrauli',
    isFeatured: false,
  },
  {
    id: 'place-jwala-devi-mandir',
    name: 'Maa Jwalamukhi Temple (Shaktinagar)',
    category: 'Temples & Culture',
    shortDescription: 'Revered historical Shakti Peeth temple drawing pilgrims and devotees from throughout central India.',
    heroImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    lat: 24.1481,
    lng: 82.7812,
    approxDistanceKm: 28.0,
    approxDriveMinutes: 50,
    address: 'Shaktinagar Border, Near Singrauli',
    openingHours: '05:00 AM – 09:00 PM daily',
    travelTips: 'Special aarti ceremonies at sunrise and dusk.',
    googleMapsQuery: 'Jwalamukhi Temple Shaktinagar',
    isFeatured: true,
  },
];

export const initialGallery: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Warm Welcoming Facade',
    category: 'Exterior',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    caption: 'Hotel Udika Palace facade at dusk, welcoming guests along Thana Road, Waidhan.',
    isFeatured: true,
    order: 1,
  },
  {
    id: 'gal-2',
    title: 'Executive Suite Experience',
    category: 'Rooms',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    caption: 'Sophisticated interior styling in our Executive category.',
    isFeatured: true,
    order: 2,
  },
  {
    id: 'gal-3',
    title: 'Zayka Dining Ambiance',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    caption: 'Comfortable family and business dining at Zayka Restaurant.',
    isFeatured: true,
    order: 3,
  },
  {
    id: 'gal-4',
    title: 'Tandoori & Kebabs Craft',
    category: 'Food',
    imageUrl: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=1200&q=80',
    caption: 'Freshly prepared clay oven delicacies by our kitchen team.',
    isFeatured: false,
    order: 4,
  },
  {
    id: 'gal-5',
    title: 'Grand Banquet Arrangements',
    category: 'Banquet',
    imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
    caption: 'Lavish floral styling and seating setups for evening celebrations.',
    isFeatured: true,
    order: 5,
  },
  {
    id: 'gal-6',
    title: 'Deluxe AC Room Bedding',
    category: 'Rooms',
    imageUrl: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
    caption: 'Clean, sanitized linens and soothing room decor.',
    isFeatured: false,
    order: 6,
  },
  {
    id: 'gal-7',
    title: 'Authentic Indian Curry & Breads',
    category: 'Food',
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1200&q=80',
    caption: 'Dal Makhani and rich gravies made fresh daily.',
    isFeatured: false,
    order: 7,
  },
  {
    id: 'gal-8',
    title: 'Reception & Hospitality Desk',
    category: 'Interior',
    imageUrl: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80',
    caption: '24-hour reception desk staffed by courteous personnel.',
    isFeatured: false,
    order: 8,
  },
];

export const initialOffers: SpecialOffer[] = [
  {
    id: 'offer-direct-save',
    title: 'Direct Website Privilege',
    badge: 'Direct Benefit',
    discountText: 'Complimentary Early Check-in & In-Room Tea Station',
    description: 'Book your stay directly via our website or WhatsApp desk to enjoy priority room allocation and flexible check-in windows.',
    validUntil: 'Valid throughout the season',
    terms: 'Applicable on Deluxe, Super Deluxe, and Executive room requests made through the official portal.',
    ctaText: 'Enquire via WhatsApp',
    isActive: true,
  },
  {
    id: 'offer-corp-stay',
    title: 'Corporate Long-Stay Tariff',
    badge: 'Business',
    discountText: 'Special Rates for Mining & Energy Delegations',
    description: 'Special customized billing and laundry privileges for engineers, managers, and contractors visiting Singrauli on multi-day projects.',
    validUntil: 'Corporate booking agreement',
    terms: 'Minimum 4-night stay requirement with company GST billing provided.',
    ctaText: 'Contact Corporate Desk',
    isActive: true,
  },
];
